name: Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'ClinicManagerSetup.exe'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest release tag
        id: latest_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
          token: ${{ github.token }}

      - name: Set the version
        id: version
        run: |
          LATEST_VERSION=${{ steps.latest_release.outputs.tag }}
          if [[ "$LATEST_VERSION" == "" ]]; then
            VERSION="1.0.0"
          else
            # Assume the tag is semantic (vMAJOR.MINOR.PATCH) and increment the minor version
            BASE_VERSION=${LATEST_VERSION#v}
            MAJOR=$(echo $BASE_VERSION | cut -d '.' -f1)
            MINOR=$(echo $BASE_VERSION | cut -d '.' -f2)
            PATCH=$(echo $BASE_VERSION | cut -d '.' -f3)
            let "MINOR+=1"
            VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          echo "Next Version: $VERSION"
          echo "::set-output name=version::v$VERSION"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: |
            dist/ClinicManager Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
